# Import Catppuccin Mocha Theme
import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
]

# Set shell
[shell]
program="/bin/zsh"

# Set true color
[env]
TERM = "xterm-256color"

# Set window padding
[window]
startup_mode = "Maximized"
padding = { x = 12, y = 12 }

# Font settings
[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 14.0

# Set keybindings
[keyboard]
bindings = [{ key = "f", mods = "Control", action = "ToggleFullScreen" }]
